# SPDX-License-Identifier:	GPL-2.0+

obj-$(CONFIG_TI_AEMIF) += ti-aemif.o
obj-$(CONFIG_AST_CAM_SDMC)	+= ast-cam-sdmc.o
obj-$(CONFIG_MACH_ASPEED_G4)	+= aspeed-sdmc.o
obj-$(CONFIG_MACH_ASPEED_G5)	+= aspeed-sdmc.o
obj-$(CONFIG_MACH_ASPEED_G6)	+= aspeed-sdmc.o
